# add your desired knowledge graph components here

gene:
    represented_as: node
    preferred_id: ensembl
    input_label: Gene

# disease:
#     represented_as: node
#     preferred_id: doid
#     input_label: do_disease

homologous_to:
    is_a: GeneToGeneHomologyAssociation
    represented_as: edge
    input_label: IS_HOMOLOGOUS_TO

# protein to disease association:
#     is_a: association
#     represented_as: edge
#     input_label: protein_disease_association
