# add your desired knowledge graph components here

gene:
    represented_as: node
    preferred_id: ensembl
    input_label: Gene

go term:
    is_a: ontology class
    represented_as: node
    preferred_id: go
    input_label: GO_term

# disease:
#     represented_as: node
#     preferred_id: doid
#     input_label: do_disease

HOMOLOGOUS_TO:
    is_a: association
    represented_as: edge
    input_label: HOMOLOGOUS_TO

RELATED_TO:
    is_a: association
    represented_as: edge
    input_label: RELATED_TO
    
# protein to disease association:
#     is_a: association
#     represented_as: edge
#     input_label: protein_disease_association
